[theme]
base = "light"
primaryColor = "#0093D0"
backgroundColor = "#EAF3FF"
secondaryBackgroundColor = "#F4EFFF"
textColor = "#0B1B3F"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
